//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TemplateHeaderAndFooter {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TemplateHeaderAndFooter() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmailTemplateUI.Resources.TemplateHeaderAndFooter", typeof(TemplateHeaderAndFooter).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&lt;/td&gt;&lt;/tr&gt;&lt;/tbody&gt;    
        ///            &lt;/table&gt;&lt;/th&gt;&lt;/tr&gt;&lt;/tbody&gt;    
        ///            &lt;/table&gt;&lt;/div&gt;&lt;/td&gt; &lt;/tr&gt;&lt;/tbody&gt;    
        ///            &lt;/table&gt; &lt;/td&gt;&lt;/tr&gt;&lt;tr id=&quot;&quot;section_3&quot;&quot; class=&quot;&quot;flexible-section&quot;&quot; data-columns=&quot;&quot;1&quot;&quot;&gt;&lt;td width=&quot;&quot;100%&quot;&quot; class=&quot;&quot;blk_container bmeHolder&quot;&quot; name=&quot;&quot;bmePreFooter&quot;&quot; valign=&quot;&quot;top&quot;&quot; align=&quot;&quot;center&quot;&quot; bgcolor=&quot;&quot;#ffffff&quot;&quot; style=&quot;&quot;background-color: rgb(255, 255, 255);   &quot;&quot;&gt;&lt;div id=&quot;&quot;dv_9&quot;&quot; class=&quot;&quot;blk_wrapper&quot;&quot; style=&quot;&quot;&quot;&quot;&gt;    
        ///            &lt;table cellspacing=&quot;&quot;0&quot;&quot; cellpadding=&quot;&quot;0&quot;&quot; borde [rest of string was truncated]&quot;;.
        /// </summary>
        public static string templateFooter {
            get {
                return ResourceManager.GetString("templateFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&lt;html xmlns=&quot;&quot;http://www.w3.org/1999/xhtml&quot;&quot;&gt;&lt;head&gt;&lt;meta http-equiv=&quot;&quot;Content-Type&quot;&quot; content=&quot;&quot;text/html; charset=utf-8&quot;&quot;&gt;
        ///    &lt;meta name=&quot;&quot;googlebot&quot;&quot; content=&quot;&quot;noindex&quot;&quot;&gt;
        ///    
        ///    &lt;title&gt;[Subject]&lt;/title&gt;
        ///    &lt;link rel=&quot;&quot;shortcut icon&quot;&quot; href=&quot;&quot;favicon.ico&quot;&quot;&gt;
        ///    
        ///    &lt;style type=&quot;&quot;text/css&quot;&quot;&gt;
        ///    table[name=&apos;blk_permission&apos;], table[name=&apos;blk_footer&apos;] {{display:none;}}
        ///    &lt;/style&gt;
        ///    &lt;/head&gt;
        ///
        ///    &lt;body topmargin=&quot;&quot;0&quot;&quot; leftmargin=&quot;&quot;0&quot;&quot; marginheight=&quot;&quot;0&quot;&quot; marginleft=&quot;&quot;0&quot;&quot; style=&quot;&quot;height: 100% ! [rest of string was truncated]&quot;;.
        /// </summary>
        public static string templateHeader {
            get {
                return ResourceManager.GetString("templateHeader", resourceCulture);
            }
        }
    }
}
